---
- name: artifactory
  docker:
    name: artifactory
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    restart_policy: always
    ports:
      - 80:8081
    volumes:
      - /opt/docker_data/artifactory_main:/var/opt/jfrog/artifactory
...