---
- name: gitlab container
  docker:
    name: gitlab-server
    image: gitlab/gitlab-ee:latest
    hostname: gitlab-server
    restart_policy: always
    ports:
      # - 80:80
      # - 443:443
      - "2222:22"
    env:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "{{gitlab_url}}"
    volumes:
      - "{{docker_volume}}/gitlab_config:/etc/gitlab"
      - "{{docker_volume}}/gitlab_logs:/var/log/gitlab"
      - "{{docker_volume}}/gitlab_data:/var/opt/gitlab"
  tags:
    - gitlab
...