---
- name: destory previous grid
  shell: |
    for i in $(docker ps | grep selenium | awk '{print $1}')
      do
        echo "Killing {i}..."
        docker stop $i
        docker rm $i
    done

- name: grid container
  docker:
    name: selenium-hub
    image: "selenium/hub:{{selenium_version}}"
    hostname: selenium-hub
    restart_policy: always
    expose:
      - "4444"
    ports:
      - "4444:4444"
    net: "{{ docker_network }}"
    env:
      GRID_TIMEOUT: 10

- name: node container
  docker:
    name: "node-{{selenium_browser}}_{{item}}"
    image: "selenium/node-{{selenium_browser}}:{{selenium_version}}"
    hostname: "node-{{selenium_browser}}_{{item}}"
    restart_policy: always
    expose:
      - "5555"
    ports:
      - "590{{item}}:5900"
    net: "{{ docker_network }}"
    env:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
  with_sequence: "start=1 end={{selenium_capacity}}"

...