---
- name: Install requirements
  apt:
    pkg:
      - ca-certificates
      - apt-transport-https
      - python3-pip
    state: present
    update_cache: true
    

- name: Add gpg key for docker
  apt_key:
    id: 0EBFCD88
    keyserver: "keyserver.ubuntu.com"
    state: present

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"

- name: Install docker
  apt:
    pkg:
      - docker-ce-cli
      - containerd.io
      - docker-ce
    state: present
    update_cache: true

- name: Enable doker service
  service:
    name: docker
    state: started
    enabled: true

- name: Enable docker user
  user:
    name: "{{ansible_user_id}}"
    group: docker
    append: yes

- name: install docker-py
  pip:
    name: docker-py
...