---
- name: Install requirements
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - ca-certificates
    - apt-transport-https
    - python-pip

- name: Add gpg key for docker
  apt_key:
    id: 0EBFCD88
    keyserver: "keyserver.ubuntu.com"
    state: present

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"

- name: Install docker
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - docker-ce

- name: Enable doker service
  service:
    name: docker
    state: started
    enabled: true

- name: Enable docker user
  user:
    name: "{{ansible_user}}"
    group: docker
    append: yes

- name: install docker-py
  pip:
    name: docker-py
    version: 1.1.0
    
- name: create service data directory
  file:
    path: "{{docker_volume}}"
    group: docker
    mode: 775
    state: directory

- include: "gitlab.yml"
- include: "nexus.yml"
- include: "nginx.yml"
...    